import { 
  Play,
  Pause,
  Volume2,
  VolumeX,
  Maximize2,
  Minimize2,
  Settings,
  RotateCw,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Loader2,
  AlertCircle,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Clock,
  User,
  LogOut,
  Upload,
  Video,
  Image,
  FileText,
  Plus,
  Trash2,
  Edit,
  Eye,
  EyeOff,
  Menu,
  Search,
  Filter,
  ArrowRight,
  ArrowLeft,
  CheckCircle,
  XCircle,
  Info,
  ExternalLink,
  Copy,
  Download,
  Heart,
  MessageSquare,
  MoreHorizontal,
  Send,
  Smile,
  Star,
  UserPlus,
  Users,
  VideoOff,
  WifiOff,
  Zap,
  ZapOff,
  type LucideIcon
} from 'lucide-react';

export const Icons = {
  play: Play,
  pause: Pause,
  volume: Volume2,
  volumeMute: VolumeX,
  maximize: Maximize2,
  minimize: Minimize2,
  settings: Settings,
  refresh: RotateCw,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  loader: Loader2,
  alert: AlertCircle,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  share: Share2,
  clock: Clock,
  user: User,
  logOut: LogOut,
  upload: Upload,
  video: Video,
  image: Image,
  fileText: FileText,
  plus: Plus,
  trash: Trash2,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  menu: Menu,
  search: Search,
  filter: Filter,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  info: Info,
  externalLink: ExternalLink,
  copy: Copy,
  download: Download,
  heart: Heart,
  messageSquare: MessageSquare,
  moreHorizontal: MoreHorizontal,
  send: Send,
  smile: Smile,
  star: Star,
  thumbUp: ThumbsUp,
  thumbDown: ThumbsDown,
  userPlus: UserPlus,
  users: Users,
  videoOff: VideoOff,
  wifiOff: WifiOff,
  zap: Zap,
  zapOff: ZapOff,
} as const;

export type IconName = keyof typeof Icons;
